repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.4
  hooks:
  - id: reorder-python-imports
    language: python
    language_version: python
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language: python
    language_version: python
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: flake8
    args: ['--ignore=E203,E266,E501,W503', '--max-line-length=88', '--max-complexity=15', '--select=B,C,E,F,W,T4,B9']
    language: python
    language_version: python